<!DOCTYPE html>
<html lang="pt-br">
<head>
<meta charset="UTF-8">
<title>Login</title>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body class="bg-dark d-flex justify-content-center align-items-center" style="height:100vh;">

<div class="card p-4 shadow" style="width:300px;">
    <h4 class="text-center">Login</h4>

    <form action="dashboard.php">
        <input class="form-control mb-2" type="email" placeholder="Email">
        <input class="form-control mb-2" type="password" placeholder="Senha">
        <button class="btn btn-primary w-100">Entrar</button>
    </form>
</div>

</body>
</html>